kind: pipeline

steps:
- name: compile
  image: microsoft/dotnet:sdk
  commands:
    - sh build.sh
- name: build-image
  image: plugins/docker
  settings:
    username: bumblefeng
    password: 7718b26a-aaf6-4a4f-9fee-34d4f0a11d90
    repo: dotnetcore-container
    dockerfile: Web/Dockerfile